name: docs
on:
  push:
    branches:
      - main
    tags: ["*"]
  pull_request:
jobs:
  docs:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo For we dont build the docs, when ready uncomment steps below in .github/workflow/docs.yml
#     steps:
#       - uses: actions/checkout@v2
#       - uses: julia-actions/setup-julia@v1
#         with:
#           version: "1"
#       - uses: julia-actions/julia-buildpkg@v1
#       - uses: julia-actions/julia-docdeploy@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
#       - run: |
#           julia --project=docs -e '
#             using Documenter: DocMeta, doctest
#             using MagneticLaplacianSparsifier
#             DocMeta.setdocmeta!(MagneticLaplacianSparsifier, :DocTestSetup, :(using MagneticLaplacianSparsifier); recursive=true)
#             doctest(MagneticLaplacianSparsifier)'
